version: '3'

services:
  web:
    volumes:
      - ./web/js/env.production.js:/usr/share/nginx/html/js/env.js:ro

  admin:
    volumes:
      - ./admin/js/env.production.js:/usr/share/nginx/html/js/env.js:ro

  api:
    environment:
      - NODE_ENV=production
