version: '3'

services:
  web:
    volumes:
      - ./web/js/env.production.js:/usr/share/nginx/html/js/env.js:ro
    restart: always

  admin:
    volumes:
      - ./admin/js/env.production.js:/usr/share/nginx/html/js/env.js:ro
    restart: always

  api:
    environment:
      - NODE_ENV=production
    restart: always

  db:
    restart: always
